development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: buybuddy
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: buybuddy
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: buybuddy
  password:

cucumber:
  <<: *TEST